"""empty message

Revision ID: 216e98c0590c
Revises: 
Create Date: 2019-08-11 18:49:34.536985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216e98c0590c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jns_tagihan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_jns_tagihan', sa.String(length=50), nullable=False),
    sa.Column('deleted_jns_tagihan', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_jns_tagihan')
    )
    op.create_table('m_pengguna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('deleted_pegawai', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('m_prodi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_prodi', sa.String(length=20), nullable=False),
    sa.Column('deleted_prodi', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('m_mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_prodi', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=True),
    sa.Column('tahun_masuk', sa.Date(), nullable=True),
    sa.Column('semester_mhs', sa.Integer(), nullable=False),
    sa.Column('status_aktif', sa.Boolean(), nullable=True),
    sa.Column('deleted_mhs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_prodi'], ['m_prodi.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama')
    )
    op.create_table('m_tagihan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_jns_tagihan', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('deleted_tagihan', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_jns_tagihan'], ['jns_tagihan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tr_tagihan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tagihan', sa.Integer(), nullable=False),
    sa.Column('id_pegawai', sa.Integer(), nullable=False),
    sa.Column('id_mahasiswa', sa.Integer(), nullable=False),
    sa.Column('tgl_tagihan', sa.Date(), nullable=True),
    sa.Column('jumlah_kurang', sa.Integer(), nullable=True),
    sa.Column('deleted_tr_tagihan', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_mahasiswa'], ['m_mahasiswa.id'], ),
    sa.ForeignKeyConstraint(['id_pegawai'], ['m_pengguna.id'], ),
    sa.ForeignKeyConstraint(['id_tagihan'], ['m_tagihan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tr_pembayaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tr_tagihan', sa.Integer(), nullable=False),
    sa.Column('id_pegawai', sa.Integer(), nullable=False),
    sa.Column('tgl_pembayaran', sa.Date(), nullable=True),
    sa.Column('jumlah_bayar', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('deleted_tr_pembayaran', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pegawai'], ['m_pengguna.id'], ),
    sa.ForeignKeyConstraint(['id_tr_tagihan'], ['tr_tagihan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tr_pembayaran')
    op.drop_table('tr_tagihan')
    op.drop_table('m_tagihan')
    op.drop_table('m_mahasiswa')
    op.drop_table('m_prodi')
    op.drop_table('m_pengguna')
    op.drop_table('jns_tagihan')
    # ### end Alembic commands ###
